# AUTH ROUTES
### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"username": "test2",
"password": "test2"
}

### Récupération des infos de l'user (genre une page profil) || Auth guard need login
GET http://localhost:3000/auth/profil
Authorization: Bearer <token>



# USERS ROUTES
### Get all users without password (interceptors)
GET http://localhost:3000/users/

### Post User to register them in the database
POST http://localhost:3000/users/register
Content-Type: application/json

{
"userId": "4",
"username": 1,
"password": ""
}
